name: Publish Library to PlatformIO

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'   # Match tags in the vMAJOR.MINOR.PATCH format (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Publish to PlatformIO
        uses: bojit/platformio-publish@v1.0.0
        with:
          token: ${{ secrets.PLATFORMIO_TOKEN }}
