name: Publish Library to PlatformIO

on:
  release:
    types:
      - published   # Trigger only when a release is published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Tag Format
        run: |
          echo "Validating tag format: ${{ github.event.release.tag_name }}"
          if [[ ! "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag format is invalid. Must be in vMAJOR.MINOR.PATCH format (e.g., v1.0.0)."
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}  # Check out the tag associated with the release

      - name: Publish to PlatformIO
        uses: bojit/platformio-publish@v1.0.0
        with:
          token: ${{ secrets.PLATFORMIO_TOKEN }}
